#
# JDBC connection properties
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false&serverTimezone=UTC&useUnicode=true&useJDBCCompliantTimezoneShift=true;
    username: sfg_dev_user
    password: pas1
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    open-in-view: false

  resources:
    static-locations: /kowboj3f/src/main/webapp/WEB-INF/views/jsp/

#
# Initial schema generation - first startup
#
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: kowboj_database_create.sql

#
# Connection pool properties
#
connection:
  pool:
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 20
    maxIdleTime: 3000




